baseURL = "https://www.masterless.io/"
languageCode = "en-us"
title = "Masterless"

theme = ["m10c", "webmonetization"]

[params]
  monetization = "$twitter.xrptipbot.com/elias_era"
  secondTitle = "About"
  author = "Elias"
  description = "Software Engineer, working in Ireland. Interested in libre software, workplace autonomy and solidarity economy."

[[params.social]]
  name = "rss"
  url = "https://www.masterless.io/posts/index.xml"

[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/elias-de-oliveira-granja-junior-23a19020/"

[[params.social]]
  name = "mail"
  url = "mailto:brtechie@protonmail.com"

[[params.social]]
  name = "inbox"
  url = "https://keybase.io/eliasjr"

[[params.social]]
  name = "github"
  url = "https://github.com/era"

[params.style]
  darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#fff"
